### ISSUE TITLE
Error: Cannot find module '../lib/path.js'

### ISSUE THREAD

**Issue by kumavis** [wanderer/edt#1]
Error on fresh clone

```
╭─{👻 } kumavis in ~/Development/Node/edt on (master) 
╰─± ./bin/bcm --cpp

module.js:340
    throw err;
    ^
Error: Cannot find module '../lib/path.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kumavis/Development/Node/edt/bin/bcm:52:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by kumavis** [comment]
files does not exist yo

**Comment by wanderer** [comment]
thanks @kumavis ! should be fixed now
